name: pixlstudio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
  fonts:
    - family: Pixelify Sans
      fonts:
        - asset: assets/fonts/Pixelify_Sans/PixelifySans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pixelify_Sans/PixelifySans-Bold.ttf
          weight: 700
        

